name: sam_3d_body
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - blas=1.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.7.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - numpy=2.2.5
  - numpy-base=2.2.5
  - ocl-icd=2.3.3
  - opencl-headers=2025.07.22
  - openh264=2.1.1
  - openssl=3.0.18
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - x264=1!157.20191217
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - appdirs==1.4.4
      - appnope==0.1.4
      - async-timeout==5.0.1
      - attrs==25.4.0
      - black==25.11.0
      - braceexpand==0.1.7
      - brotli==1.2.0
      - chump==1.6.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.2.2
      - detectron2==0.6
      - dill==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - fastapi==0.123.0
      - ffmpeg==1.4
      - ffmpy==1.0.0
      - filelock==3.20.1
      - fonttools==4.61.0
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glcontext==3.0.0
      - gradio==6.0.1
      - gradio-client==2.0.0
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - imageio==2.37.2
      - iniconfig==2.3.0
      - iopath==0.1.10
      - joblib==1.5.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - loguru==0.7.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - moderngl==5.12.0
      - moge==2.0.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - optree==0.18.0
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pipeline==1.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - pycocotools==2.0.10
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyglet==2.1.11
      - pygments==2.19.2
      - pyopengl==3.1.0
      - pyparsing==3.2.5
      - pyrender==0.1.45
      - pyrootutils==1.0.4
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytokens==0.3.0
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - rich==14.2.0
      - roma==1.5.4
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.46.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - starlette==0.50.0
      - submitit==1.5.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.5.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - trimesh==4.10.0
      - typer==0.20.0
      - typer-slim==0.21.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - utils3d==1.3
      - uvicorn==0.38.0
      - wandb==0.23.0
      - webdataset==1.0.2
      - werkzeug==3.1.4
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yarl==1.22.0
prefix: /mnt/disk1/conda_envs/sam_3d_body
